// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ySXN4WpTCibS1BNnJd7sOSEd7DuRibs',
    appId: '1:458375821413:web:43e93648d576266bd46e8c',
    messagingSenderId: '458375821413',
    projectId: 'flutter-recipe-57a49',
    authDomain: 'flutter-recipe-57a49.firebaseapp.com',
    storageBucket: 'flutter-recipe-57a49.appspot.com',
    measurementId: 'G-MEX7WQY3CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDX2m4ymVK6D_yOaNuoJSdgPQfsRZdFxs',
    appId: '1:458375821413:android:09427eb19b4ac5cbd46e8c',
    messagingSenderId: '458375821413',
    projectId: 'flutter-recipe-57a49',
    storageBucket: 'flutter-recipe-57a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DdhMLxgpgJoQqIsQKQF-xSrR0ZNKbdQ',
    appId: '1:458375821413:ios:bb91e7b9926a87bed46e8c',
    messagingSenderId: '458375821413',
    projectId: 'flutter-recipe-57a49',
    storageBucket: 'flutter-recipe-57a49.appspot.com',
    iosClientId:
        '458375821413-i6prb35asqa011mf1pt1th2ekkf5p6ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DdhMLxgpgJoQqIsQKQF-xSrR0ZNKbdQ',
    appId: '1:458375821413:ios:bb91e7b9926a87bed46e8c',
    messagingSenderId: '458375821413',
    projectId: 'flutter-recipe-57a49',
    storageBucket: 'flutter-recipe-57a49.appspot.com',
    iosClientId:
        '458375821413-i6prb35asqa011mf1pt1th2ekkf5p6ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
